task :default => :cucumber

desc 'Run the tests'
task :cucumber => 'libgraycode.dylib' do
  sh 'cucumber features'
end

file 'libgraycode.dylib' => 'graycode.o' do
  sh 'g++ -shared -o libgraycode.dylib graycode.o'
end

rule '.o' => '.cpp' do |t|
  sh "g++ -I. -c #{t.source}"
end
